# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ER250/OneDrive/Documents/ECE520_SOC/ECE520_SandBox/int_gen_soc_re/int_gen_soc_re.srcs/sources_1/bd/int_gen_bd_re/ip/int_gen_bd_re_processing_system7_0_0/int_gen_bd_re_processing_system7_0_0.xci
# IP: The module: 'int_gen_bd_re_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ER250/OneDrive/Documents/ECE520_SOC/ECE520_SandBox/int_gen_soc_re/int_gen_soc_re.gen/sources_1/bd/int_gen_bd_re/ip/int_gen_bd_re_processing_system7_0_0/int_gen_bd_re_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_gen_bd_re_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ER250/OneDrive/Documents/ECE520_SOC/ECE520_SandBox/int_gen_soc_re/int_gen_soc_re.srcs/sources_1/bd/int_gen_bd_re/ip/int_gen_bd_re_processing_system7_0_0/int_gen_bd_re_processing_system7_0_0.xci
# IP: The module: 'int_gen_bd_re_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ER250/OneDrive/Documents/ECE520_SOC/ECE520_SandBox/int_gen_soc_re/int_gen_soc_re.gen/sources_1/bd/int_gen_bd_re/ip/int_gen_bd_re_processing_system7_0_0/int_gen_bd_re_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_gen_bd_re_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
