# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/int_gen_bd_re/int_gen_bd_re.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_gen_bd_re || ORIG_REF_NAME==int_gen_bd_re} -quiet] -quiet

# IP: bd/int_gen_bd_re/ip/int_gen_bd_re_processing_system7_0_0/int_gen_bd_re_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_gen_bd_re_processing_system7_0_0 || ORIG_REF_NAME==int_gen_bd_re_processing_system7_0_0} -quiet] -quiet

# IP: bd/int_gen_bd_re/ip/int_gen_bd_re_interrupt_generator_0_0/int_gen_bd_re_interrupt_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_gen_bd_re_interrupt_generator_0_0 || ORIG_REF_NAME==int_gen_bd_re_interrupt_generator_0_0} -quiet] -quiet

# IP: bd/int_gen_bd_re/ip/int_gen_bd_re_ps7_0_axi_periph_0/int_gen_bd_re_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_gen_bd_re_ps7_0_axi_periph_0 || ORIG_REF_NAME==int_gen_bd_re_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/int_gen_bd_re/ip/int_gen_bd_re_rst_ps7_0_50M_0/int_gen_bd_re_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_gen_bd_re_rst_ps7_0_50M_0 || ORIG_REF_NAME==int_gen_bd_re_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/int_gen_bd_re/ip/int_gen_bd_re_auto_pc_0/int_gen_bd_re_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int_gen_bd_re_auto_pc_0 || ORIG_REF_NAME==int_gen_bd_re_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/ER250/OneDrive/Documents/ECE520_SOC/ECE520_SandBox/int_gen_soc_re/int_gen_soc_re.gen/sources_1/bd/int_gen_bd_re/int_gen_bd_re_ooc.xdc
